<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
	<!ELEMENT text (sentence+)>
	    <!ATTLIST text id CDATA #REQUIRED>
	<!ELEMENT sentence (theme, rheme, semantic_roles)>
		<!ELEMENT theme (token*)>
		<!ELEMENT rheme (token*)>
		<!ELEMENT token (#PCDATA)>
		<!ELEMENT semantic_roles (frame*)>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="1_20000702_ssd_annotated_recursive">


	<sentence>
		<theme>
			<token>la</token><token>Real</token><token>Academia</token><token>de</token><token>la</token><token>Historia</token>
		</theme>
		<rheme>
			<token>se</token><token>equivocó</token><token>al</token><token>asegurar</token><token>que</token><token>las</token><token>comunidades</token><token>autónomas</token><token>tergiversan</token><token>el</token><token>pasado</token><token>y</token><token>silencian</token><token>el</token><token>concepto</token><token>de</token><token>España</token>
		</rheme>
		<semantic_roles>
			<frame type="Aggregate" head="comunidades"></frame>
			<frame type="Becoming_silent" head="silencian">
				<argument type="Topic" dependent="el concepto de"/></frame>
			<frame type="Correctness" head="equivocó">
				<argument type="Information" dependent="la Real Academia de la Historia"/>
				<argument type="Information" dependent="al asegurar que las comunidades autónomas tergiversan el pasado"/></frame>
			<frame type="Individual_history" head="la Historia"></frame>
			<frame type="Relative_time" head="pasado"></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>La</token><token>mayoría</token><token>de</token><token>manuales</token>
		</theme>
		<rheme>
			<token>desarrolla</token><token>el</token><token>pasado</token><token>común</token>
		</rheme>
		<semantic_roles>
			<frame type="Cause_to_make_progress" head="desarrolla">
				<argument type="Agent" dependent="mayoría de manuales"/>
				<argument type="Project" dependent="el pasado"/></frame>
			<frame type="Relative_time" head="pasado"></frame>
			<frame type="Text" head="manuales"></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>Los</token><token>libros</token><token>de</token><token>texto</token>
		</theme>
		<rheme>
			<token>ofrecen</token><token>a</token><token>los</token><token>escolares</token><token>una</token><token>visión</token><token>de</token><token>la</token><token>historia</token><token>de</token><token>España</token><token>equilibrada</token><token>,</token><token>universal</token><token>y</token><token>ajustada</token><token>al</token><token>espíritu</token><token>plural</token><token>y</token><token>democrático</token><token>inspirado</token><token>en</token><token>la</token><token>Constitución</token><token>de</token><token>1978</token>
		</rheme>
		<semantic_roles>
			<frame type="Individual_history" head="historia">
				<argument type="Events" dependent="de la"/></frame>
			<frame type="Offering" head="ofrecen">
				<argument type="Theme" dependent="ofrecen a los escolares una visión de la historia de España equilibrada, universal y ajustada al espíritu plural y democrático inspirado en la"/>
				<argument type="Potential_recipient" dependent="en la Constitución de"/></frame>
			<frame type="Subjective_influence" head="inspirado">
				<argument type="Entity" dependent="espíritu plural y democrático"/>
				<argument type="Place" dependent="en la Constitución de"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>Un</token><token>informe</token><token>de</token><token>la</token><token>Real</token><token>Academia</token><token>de</token><token>la</token><token>Historia</token><token>hecho</token><token>público</token><token>esta</token><token>semana</token>
		</theme>
		<rheme>
			<token>acusó</token><token>a</token><token>las</token><token>comunidades</token><token>autónomas</token><token>de</token><token>&quot;</token><token>tergiversar</token><token>&quot;</token><token>la</token><token>enseñanza</token><token>de</token><token>esta</token><token>disciplina</token><token>,</token><token>y</token><token>convertirla</token><token>en</token><token>&quot;</token><token>una</token><token>historia</token><token>local</token><token>,</token><token>discontinua</token><token>y</token><token>particularista</token><token>&quot;</token>
		</rheme>
		<semantic_roles>
			<frame type="Aggregate" head="comunidades"></frame>
			<frame type="Calendric_unit" head="semana"></frame>
			<frame type="Cause_change" head="convertirla">
				<argument type="Cause" dependent="enseñanza de esta disciplina"/>
				<argument type="Final_category" dependent="en una historia local, discontinua y"/></frame>
			<frame type="Individual_history" head="la Historia">
				<argument type="Time_span" dependent="discontinua y"/></frame>
			<frame type="Judgment_communication" head="tergiversar">
				<argument type="Medium" dependent="informe de la Real Academia de la Historia hecho público esta semana acusó a"/>
				<argument type="Reason" dependent="las comunidades autónomas de tergiversar la enseñanza de esta disciplina"/></frame>
			<frame type="Means" head="de la">
				<argument type="Purpose" dependent="informe de"/>
				<argument type="Means" dependent="la Real Academia de"/></frame>
			<frame type="Political_locales" head="local"></frame>
			<frame type="Rewards_and_punishments" head="disciplina"></frame>
			<frame type="Statement" head="informe de">
				<argument type="Speaker" dependent="de la Real Academia de la"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>el</token><token>informe</token>
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>La</token><token>mayor</token><token>proporción</token><token>de</token><token>temas</token><token>relativos</token><token>a</token><token>toda</token><token>España</token><token>frente</token><token>a</token><token>los</token><token>específicos</token><token>de</token><token>cada</token><token>territorio</token><token>,</token><token>la</token><token>ecuanimidad</token><token>con</token><token>que</token><token>se</token><token>explica</token><token>el</token><token>fenómeno</token><token>nacionalista</token><token>junto</token><token>a</token><token>los</token><token>hechos</token><token>históricos</token><token>comunes</token><token>,</token><token>y</token><token>el</token><token>énfasis</token><token>con</token><token>el</token><token>que</token><token>la</token><token>Constitución</token><token>y</token><token>los</token><token>correspondientes</token><token>estatutos</token><token>de</token><token>autonomía</token><token>son</token><token>presentados</token><token>como</token><token>pilares</token><token>del</token><token>régimen</token><token>democrático</token>
		</theme>
		<rheme>
			<token>desmienten</token><token>los</token><token>ejes</token><token>centrales</token><token>del</token><token>informe</token><token>de</token><token>la</token><token>academia</token>
		</rheme>
		<semantic_roles>
			<frame type="Affirm_or_deny" head="de">
				<argument type="Speaker" dependent="presentados como pilares del régimen democrático"/>
				<argument type="Message" dependent="los ejes centrales del informe de la"/></frame>
			<frame type="Collaboration" head="junto">
				<argument type="Partner_2" dependent="fenómeno nacionalista"/>
				<argument type="Partner_2" dependent="junto a los hechos históricos comunes el énfasis con el que la Constitución"/></frame>
			<frame type="Emphasizing" head="énfasis"></frame>
			<frame type="Evaluative_comparison" head="proporción">
				<argument type="Profiled_item" dependent="toda"/></frame>
			<frame type="Explaining_the_facts" head="explica">
				<argument type="Fact" dependent="el fenómeno nacionalista"/></frame>
			<frame type="Leadership" head="régimen"></frame>
			<frame type="Part_inner_outer" head="centrales del"></frame>
			<frame type="Political_locales" head="territorio"></frame>
			<frame type="Statement" head="correspondientes">
				<argument type="Message" dependent="mayor proporción de temas"/>
				<argument type="Message" dependent="a toda"/></frame>
			<frame type="Statement" head="informe de"></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>Los</token><token>libros</token><token>de</token><token>texto</token><token>que</token><token>no</token><token>respetan</token><token>una</token><token>visión</token><token>neutra</token><token>y</token><token>sensata</token><token>de</token><token>la</token><token>historia</token>
		</theme>
		<rheme>
			<token>son</token><token>pura</token><token>excepción</token><token>&quot;</token>
		</rheme>
		<semantic_roles>
			<frame type="Individual_history" head="historia"></frame>
			<frame type="Judgment" head="respetan">
				<argument type="Cognizer" dependent="libros de texto que"/>
				<argument type="Evaluee" dependent="una visión neutra y sensata de la historia son pura excepción"/></frame>
			<frame type="Opinion" head="visión">
				<argument type="Opinion" dependent="la historia"/></frame>
			<frame type="Partiality" head="neutra"></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>La</token><token>academia</token>
		</theme>
		<rheme>
			<token>lamenta</token><token>&quot;</token><token>la</token><token>impresión</token><token>de</token><token>que</token><token>la</token><token>vieja</token><token>historia</token><token>de</token><token>España</token><token>se</token><token>fragmenta</token><token>en</token><token>múltiples</token><token>historias</token><token>regionales</token><token>&quot;</token><token>,</token><token>pese</token><token>a</token><token>los</token><token>criterios</token><token>comunes</token><token>y</token><token>mínimos</token><token>dictados</token><token>por</token><token>el</token><token>Ministerio</token><token>de</token><token>Educación</token>
		</rheme>
		<semantic_roles>
			<frame type="Age" head="vieja">
				<argument type="Entity" dependent="historia de"/></frame>
			<frame type="Cause_to_fragment" head="fragmenta">
				<argument type="Whole_patient" dependent="la vieja historia de"/>
				<argument type="Whole_patient" dependent="en múltiples historias regionales"/></frame>
			<frame type="Experiencer_focus" head="lamenta"></frame>
			<frame type="Individual_history" head="historia"></frame>
			<frame type="Locale" head="regionales"></frame>
			<frame type="Quantified_mass" head="múltiples">
				<argument type="Individuals" dependent="historias regionales"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>el</token><token>volumen</token><token>de</token><token>Anaya</token><token>de</token><token>la</token><token>serie</token><token>Nuestro</token><token>Mundo</token><token>,</token><token>uno</token><token>de</token><token>los</token><token>más</token><token>usados</token><token>en</token><token>las</token><token>aulas</token><token>vascas</token><token>,</token>
		</theme>
		<rheme>
			<token>excede</token><token>el</token><token>55%</token><token>de</token><token>temario</token><token>común</token><token>fijado</token><token>por</token><token>Educación</token><token>para</token><token>las</token><token>comunidades</token><token>con</token><token>lengua</token><token>propia</token>
		</rheme>
		<semantic_roles>
			<frame type="Aggregate" head="comunidades"></frame>
			<frame type="Aggregate" head="fijado"></frame>
			<frame type="Cardinal_numbers" head="uno">
				<argument type="Entity" dependent="de los más usados en las aulas vascas"/></frame>
			<frame type="Education_teaching" head="Educación">
				<argument type="Subject" dependent="para las comunidades con lengua"/></frame>
			<frame type="Interior_profile_relation" head="en">
				<argument type="Figure" dependent="uno de los más usados"/>
				<argument type="Ground" dependent="aulas vascas"/></frame>
			<frame type="Text" head="volumen de">
				<argument type="Author" dependent="Anaya"/></frame>
			<frame type="Timetable" head="temario"></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>tan</token><token>sólo</token><token>6</token><token>-</token><token>-</token><token>el</token><token>5,7%</token><token>-</token><token>-</token>
		</theme>
		<rheme>
			<token>se</token><token>centran</token><token>en</token><token>el</token><token>País</token><token>Vasco</token>
		</rheme>
		<semantic_roles>
			<frame type="Political_locales" head="País"></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>Este</token><token>manual</token><token>,</token><token>del</token><token>que</token><token>existe</token><token>la</token><token>correspondiente</token><token>versión</token><token>en</token><token>euskera</token><token>,</token>
		</theme>
		<rheme>
			<token>incluye</token><token>un</token><token>amplio</token><token>bloque</token>
		</rheme>
		<semantic_roles>
			<frame type="Inclusion" head="incluye">
				<argument type="Total" dependent="Este manual"/>
				<argument type="Total" dependent="del que"/>
				<argument type="Total" dependent="correspondiente versión en euskera"/>
				<argument type="Part" dependent="incluye"/></frame>
			<frame type="Locative_relation" head="existe">
				<argument type="Figure" dependent="Este manual"/>
				<argument type="Ground" dependent="existe la correspondiente versión en euskera"/></frame>
			<frame type="Text" head="manual"></frame>
			<frame type="Type" head="versión">
				<argument type="Category" dependent="en euskera"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>La</token><token>fabulosa</token><token>herencia</token><token>de</token><token>Carlos</token><token>V</token><token>,</token><token>la</token><token>monarquía</token><token>hispánica</token><token>y</token><token>Reyes</token><token>Poderosos</token>
		</theme>
		<rheme>
			<token>son</token><token>tres</token><token>apartados</token>
		</rheme>
		<semantic_roles>
			<frame type="Cardinal_numbers" head="tres"></frame>
			<frame type="Desirability" head="fabulosa">
				<argument type="Evaluee" dependent="herencia de Carlos V la"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token>Otro</token><token>temor</token><token>invocado</token><token>por</token><token>la</token><token>academia</token>
		</theme>
		<rheme>
			<token>es</token><token>un</token><token>posible</token><token>tratamiento</token><token>&quot;</token><token>de</token><token>todo</token><token>lo</token><token>que</token><token>nos</token><token>separa</token><token>&quot;</token><token>,</token>
		</rheme>
		<semantic_roles>
			<frame type="Cure" head="tratamiento"></frame>
			<frame type="Fear" head="temor">
				<argument type="Experiencer" dependent="por la academia"/></frame>
			<frame type="Increment" head="Otro">
				<argument type="Class" dependent="temor invocado por la academia"/></frame>
			<frame type="Likelihood" head="posible">
				<argument type="Hypothetical_event" dependent="tratamiento de todo lo que nos separa"/></frame>
		</semantic_roles>
	</sentence>


</text>