<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
	<!ELEMENT text (sentence+)>
	    <!ATTLIST text id CDATA #REQUIRED>
	<!ELEMENT sentence (theme, rheme, semantic_roles)>
		<!ELEMENT theme (token*)>
		<!ELEMENT rheme (token*)>
		<!ELEMENT token (#PCDATA)>
		    <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
		<!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="5_20000903_ssd_annotated_recursive">


	<sentence>
		<theme>
			<token pos="da0fs0">La</token><token pos="ncfs000">unificación</token><token pos="aq0fs0">italiana</token>
		</theme>
		<rheme>
			<token pos="vmis3s0">marcó</token><token pos="da0ms0">el</token><token pos="ncms000">papado</token><token pos="sps00">de</token><token pos="np0000l">Mastai</token><token pos="np0000l">Ferretti</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0mp0">Los</token><token pos="ncmp000">historiadores</token>
		</theme>
		<rheme>
			<token pos="vmip3p0">consideran</token><token pos="sps00">a</token><token pos="np0000l">Pío</token><token pos="np0000l">IX</token><token pos="cs">como</token><token pos="di0ms0">un</token><token pos="np00000">Papa</token><token pos="aq0cs0">popular</token><token pos="cc">y</token><token pos="aq0msp">controvertido</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
			<frame type="Desirability" head="popular">
				<argument type="Evaluee" dependent="y"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="pr0cn000">que</token>
		</theme>
		<rheme>
			<token pos="vsii3s0">era</token><token pos="da0ms0">el</token><token pos="ao0ms0">último</token><token pos="ncms000">grito</token><token pos="spcms">del</token><token pos="ncms000">progreso</token>
		</rheme>
		<semantic_roles>
			<main_frame type="Calendric_unit" head="era">
				<argument type="Whole" dependent="que"/></main_frame>
			<frame type="Substance" head="gas">
				<argument type="Descriptor" dependent="un"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="pi0fs000">una</token><token pos="da0fs0">la</token><token pos="aq0cs0">libre</token><token pos="ncfs000">discusión</token>
		</theme>
		<rheme>
			<token pos="vmip3s0">dice</token><token pos="cs">que</token><token pos="sps00">por</token><token pos="ncms000">derecho</token><token pos="aq0cs0">natural</token><token pos="da0ms0">el</token><token pos="ncms000">clero</token><token pos="rn">no</token><token pos="vmip3s0">debe</token><token pos="vmn0000">hacer</token><token pos="da0fs0">la</token><token pos="ncfs000">mili</token><token pos="vmip3s0">corrompe</token><token pos="da0ms0">el</token><token pos="ncfs000">alma</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="ncms000">Juan</token><token pos="np0000o">María</token><token pos="ncms000">Mastai</token><token pos="np0000a">Ferretti</token><token pos="pr0cn000">que</token>
		</theme>
		<rheme>
			<token pos="vaii3s0">había</token><token pos="vmp00sm">nacido</token><token pos="sps00">en</token><token pos="np00000">Senigallia</token><token pos="da0ms0">el</token><token pos="ncmp000">año</token><token pos="zm">1792</token><token pos="vmis3p0">contribuyeron</token><token pos="sps00">a</token><token pos="vmn0000">darle</token><token pos="di0ms0">un</token><token pos="ncms000">carácter</token><token pos="aq0msp">retraído</token>
		</rheme>
		<semantic_roles>
			<frame type="Catastrophe" head="crisis">
				<argument type="Undesirable_event" dependent="a darle un"/></frame>
			<frame type="Catastrophe" head="crisis">
				<argument type="Undesirable_event" dependent="a darle un"/></frame>
			<frame type="Catastrophe" head="crisis">
				<argument type="Undesirable_event" dependent="a darle un"/></frame>
			<frame type="Catastrophe" head="crisis">
				<argument type="Undesirable_event" dependent="a darle un"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="np0000l">Pío</token><token pos="np0000l">IX</token>
		</theme>
		<rheme>
			<token pos="vmis3s0">empezó</token><token pos="dp3cs0">su</token><token pos="ncms000">pontificado</token><token pos="sps00">con</token><token pos="aq0cp0">grandes</token><token pos="ncmp000">proyectos</token><token pos="sps00">para</token><token pos="vmn0000">reformar</token><token pos="da0ms0">el</token><token pos="ncms000">clero</token><token pos="fc">,</token><token pos="vmn0000">poner</token><token pos="ncfs000">orden</token><token pos="sps00">a</token><token pos="da0fs0">la</token><token pos="ncfs000">diplomacia</token><token pos="aq0fs0">vaticana</token><token pos="cc">y</token><token pos="vmn0000">potenciar</token><token pos="da0fp0">las</token><token pos="ncfp000">misiones</token><token pos="aq0fp0">católicas</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="dp3cs0">Su</token><token pos="ncms000">carisma</token>
		</theme>
		<rheme>
			<token pos="pp3csd00">le</token><token pos="vmis3s0">dio</token><token pos="di0fs0">mucha</token><token pos="ncfs000">popularidad</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="np0000l">Pío</token><token pos="np0000l">IX</token>
		</theme>
		<rheme>
			<token pos="vmis3s0">reaccionó</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="pr0mp000">cuyos</token><token pos="ncmp000">seguidores</token><token pos="sps00">en</token><token pos="np00000">Roma</token>
		</theme>
		<rheme>
			<token pos="vmii3p0">seguían</token><token pos="vmg0000">viviendo</token><token pos="sps00">en</token><token pos="ncmp000">guetos</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="np0000l">Pío</token><token pos="np0000l">IX</token>
		</theme>
		<rheme>
			<token pos="vmis3s0">proclamó</token><token pos="da0ms0">el</token><token pos="ncms000">dogma</token><token pos="fpa">(</token><token pos="ncfs000">verdad</token><token pos="aq0cs0">indiscutible</token><token pos="fpt">)</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="np0000l">Inmaculada</token><token pos="np0000l">Concepción</token><token pos="fc">,</token><token pos="cc">o</token><token pos="vsis3s0">sea</token><token pos="cs">que</token><token pos="da0fs0">la</token><token pos="ncms000">virgen</token><token pos="np00000">María</token><token pos="vaic3s0">habría</token><token pos="vmp00sm">nacido</token><token pos="sps00">sin</token><token pos="ncms000">pecado</token><token pos="aq0cs0">original</token><token pos="fc">,</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
			<frame type="Misdeed" head="sin">
				<argument type="Manner" dependent="la virgen"/>
				<argument type="Wrongdoer" dependent="pecado original"/></frame>
			<frame type="Misdeed" head="sin">
				<argument type="Manner" dependent="la virgen"/>
				<argument type="Wrongdoer" dependent="pecado original"/></frame>
			<frame type="Misdeed" head="sin">
				<argument type="Manner" dependent="la virgen"/>
				<argument type="Wrongdoer" dependent="pecado original"/></frame>
			<frame type="Misdeed" head="sin">
				<argument type="Manner" dependent="la virgen"/>
				<argument type="Wrongdoer" dependent="pecado original"/></frame>
			<frame type="Natural_features" head="sea">
				<argument type="Descriptor" dependent="o"/></frame>
			<main_frame type="Natural_features" head="sea">
				<argument type="Descriptor" dependent="o"/></main_frame>
			<frame type="Natural_features" head="sea">
				<argument type="Descriptor" dependent="o"/></frame>
			<frame type="Natural_features" head="sea">
				<argument type="Descriptor" dependent="o"/></frame>
		</semantic_roles>
	</sentence>


</text>