<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
	<!ELEMENT text (sentence+)>
	    <!ATTLIST text id CDATA #REQUIRED>
	<!ELEMENT sentence (theme, rheme, semantic_roles)>
		<!ELEMENT theme (token*)>
		<!ELEMENT rheme (token*)>
		<!ELEMENT token (#PCDATA)>
		    <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
		<!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="5_20010302_ssd_annotated_recursive">


	<sentence>
		<theme>
			<token pos="da0fs0">La</token><token pos="aq0cs0">gran</token><token pos="ncfs000">banca</token>
		</theme>
		<rheme>
			<token pos="vsp00sm">sido</token><token pos="rg">muy</token><token pos="aq0fs0">activa</token><token pos="spcms">al</token><token pos="vmn0000">implantar</token><token pos="dp3cp0">sus</token><token pos="ncfp000">actividades</token><token pos="spcms">al</token><token pos="di0ms0">otro</token><token pos="ncms000">lado</token><token pos="spcms">del</token><token pos="np00000">Atlántico</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="np00000">BBVA</token><token pos="cc">y</token><token pos="np00000">BSCH</token>
		</theme>
		<rheme>
			<token pos="vaip3p0">han</token><token pos="vmp00sm">integrado</token><token pos="sps00">en</token><token pos="dp3cp0">sus</token><token pos="ncfp000">estructuras</token><token pos="ncmp000">bancos</token><token pos="sps00">de</token><token pos="da0fs0">la</token><token pos="ncfs000">región</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0ms0">el</token><token pos="np00000">BBVA</token>
		</theme>
		<rheme>
			<token pos="sps00">En</token><token pos="np00000">México</token><token pos="vaip3s0">ha</token><token pos="vmp00sm">incorporado</token><token pos="np00000">Bancomer</token><token pos="fc">,</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="dn0fp0">Ambas</token><token pos="ncfp000">adquisiciones</token>
		</theme>
		<rheme>
			<token pos="vmis3p0">tuvieron</token><token pos="di0ms0">un</token><token pos="ncms000">coste</token><token pos="aq0msp">elevado</token><token pos="fp">.</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


</text>