<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
	<!ELEMENT text (sentence+)>
	    <!ATTLIST text id CDATA #REQUIRED>
	<!ELEMENT sentence (theme, rheme, semantic_roles)>
		<!ELEMENT theme (token*)>
		<!ELEMENT rheme (token*)>
		<!ELEMENT token (#PCDATA)>
		    <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame*)>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="t4-7_ssd_annotated_recursive">


	<sentence>
		<theme>
			<token pos="ncms000">Jorge</token><token pos="np00000">Manrique</token>
		</theme>
		<rheme>
			<token pos="p0300000">se</token><token pos="vmip3s0">equivoca</token>
		</rheme>
		<semantic_roles>
			<frame type="Correctness" head="equivoca">
				<argument type="Communicative_act" dependent="En mi caso"/>
				<argument type="Information" dependent="Manrique"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="dp1fsp">Nuestra</token><token pos="ncfs000">sombra</token>
		</theme>
		<rheme>
			<token pos="pp1cp000">nos</token><token pos="vmip3s0">habla</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0fs0">La</token><token pos="ncms000">iniciación</token><token pos="sps00">en</token><token pos="da0ms0">el</token><token pos="ncms000">mal</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="rg">más</token><token pos="aq0cs0">importante</token><token pos="cs">que</token><token pos="sps00">en</token><token pos="da0ms0">el</token><token pos="ncms000">bien</token>
		</rheme>
		<semantic_roles>
			<frame type="Buildings" head="iglesia"></frame>
			<frame type="Locale_by_use" head="escuela"></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0fp0">Las</token><token pos="ncfp000">guerras</token><token pos="aq0fp0">destructoras</token>
		</theme>
		<rheme>
			<token pos="vmip3p0">nacen</token><token pos="spcms">del</token><token pos="ncms000">odio</token><token pos="cc">y</token><token pos="da0fs0">la</token><token pos="ncfs000">codicia</token>
		</rheme>
		<semantic_roles>
			<frame type="Bringing" head="nacen">
				<argument type="Theme" dependent="guerras destructoras"/>
				<argument type="Theme" dependent="odio y la codicia"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0ms0">El</token><token pos="ncms000">prestigio</token><token pos="sps00">de</token><token pos="da0fp0">las</token><token pos="ncfp000">aves</token><token pos="sps00">desde</token><token pos="da0fs0">la</token><token pos="ncfs000">paloma</token><token pos="sps00">hasta</token><token pos="da0ms0">el</token><token pos="ncfs000">águila</token><token pos="fc">,</token><token pos="da0ms0">el</token><token pos="ncms000">quetzal</token><token pos="cc">y</token><token pos="da0ms0">el</token><token pos="ncmn000">albatros</token>
		</theme>
		<rheme>
			<token pos="p0300000">se</token><token pos="vmip3s0">basa</token><token pos="sps00">en</token><token pos="cs">que</token><token pos="vmip3p0">pueden</token><token pos="vmn0000">vencer</token><token pos="rg">fácilmente</token><token pos="da0fs0">la</token><token pos="ncfs000">gravedad</token><token pos="cc">y</token><token pos="vmip3p0">viven</token><token pos="sps00">entre</token><token pos="da0fs0">la</token><token pos="ncfs000">tierra</token><token pos="cc">y</token><token pos="da0ms0">el</token><token pos="ncms000">cielo</token>
		</rheme>
		<semantic_roles>
			<frame type="Capability" head="pueden">
				<argument type="Event" dependent="vencer fácilmente la gravedad"/></frame>
			<frame type="Residence" head="viven">
				<argument type="Location" dependent="entre la tierra y el cielo"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


</text>