<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
	<!ELEMENT text (sentence+)>
	    <!ATTLIST text id CDATA #REQUIRED>
	<!ELEMENT sentence (theme, rheme, semantic_roles)>
		<!ELEMENT theme (token*)>
		<!ELEMENT rheme (token*)>
		<!ELEMENT token (#PCDATA)>
		    <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame|main_frame)*>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT main_frame (argument*)>
            <!ATTLIST main_frame type CDATA #REQUIRED>
            <!ATTLIST main_frame head CDATA #REQUIRED>
		<!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="t4-9_ssd_annotated_recursive">


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="pr0cn000">que</token>
		</theme>
		<rheme>
			<token pos="vmip3p0">pasan</token><token pos="da0ms0">el</token><token pos="ncms000">día</token>
		</rheme>
		<semantic_roles>
			<frame type="Boundary" head="bordeada">
				<argument type="Boundary" dependent="mi calle"/>
				<argument type="Entities" dependent="de frondosos árboles"/></frame>
			<frame type="Calendric_unit" head="día"></frame>
			<frame type="Completeness" head="lleno de">
				<argument type="Whole" dependent="de palomas"/></frame>
			<frame type="Experiencer_focus" head="amándose">
				<argument type="Content" dependent="amándose"/></frame>
			<frame type="Increment" head="de un"></frame>
			<frame type="Locale_by_use" head="parque"></frame>
			<frame type="Locative_relation" head="cerca de">
				<argument type="Ground" dependent="un parque lleno de palomas"/></frame>
			<frame type="Locative_relation" head="hay">
				<argument type="Figure" dependent="frondosos árboles"/>
				<argument type="Ground" dependent="hay sino tórtolas que pasan el día arrullándose y amándose"/></frame>
			<frame type="Performers_and_roles" head="en">
				<argument type="Performance" dependent="sino tórtolas que pasan el día arrullándose y amándose"/></frame>
			<frame type="Residence" head="Vivo">
				<argument type="Location" dependent="cerca de un parque lleno de palomas"/></frame>
			<frame type="Roadways" head="calle"></frame>
			<frame type="Sole_instance" head="pero">
				<argument type="Item" dependent="tórtolas que pasan el día arrullándose y amándose"/></frame>
			<frame type="Spatial_contact" head="en">
				<argument type="Ground" dependent="mi calle"/>
				<argument type="Figure" dependent="bordeada de frondosos árboles no hay sino tórtolas que pasan el día arrullándose y amándose"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0ms0">El</token><token pos="ncms000">sexo</token>
		</theme>
		<rheme>
			<token pos="pp3cpd00">les</token><token pos="vmip3s0">da</token><token pos="ncfs000">calidad</token><token pos="cc">y</token><token pos="ncfs000">dimensión</token><token pos="aq0fs0">lírica</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="np0000l">España</token>
		</theme>
		<rheme>
			<token pos="vsip3s0">es</token><token pos="di0ms0">un</token><token pos="ncms000">país</token><token pos="sps00">de</token><token pos="ncmp000">oradores</token><token pos="aq0cp0">fúnebres</token>
		</rheme>
		<semantic_roles>
			<frame type="Certainty" head="no">
				<argument type="Content" dependent="que no los oye y sobre todo de que no va a resucitar"/></frame>
			<frame type="Dead_or_alive" head="muerto"></frame>
			<frame type="Directional_locative_relation" head="sobre el">
				<argument type="Ground" dependent="todo de que no va a resucitar"/></frame>
			<frame type="Perception_experience" head="oye"></frame>
			<frame type="Political_locales" head="país">
				<argument type="Name" dependent="de oradores fúnebres"/></frame>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0mp0">Los</token><token pos="ncmp000">boxeadores</token>
		</theme>
		<rheme>
			<token pos="vsip3p0">son</token><token pos="da0mp0">los</token><token pos="aq0mp0">únicos</token>
		</rheme>
		<semantic_roles>
			<frame type="Similarity" head="como">
				<argument type="Entity_1" dependent="los únicos que dicen verdades"/></frame>
			<frame type="Sole_instance" head="únicos que"></frame>
			<frame type="Statement" head="dicen">
				<argument type="Speaker" dependent="los únicos que"/></frame>
		</semantic_roles>
	</sentence>


</text>