<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE text [
	<!ELEMENT text (sentence+)>
	    <!ATTLIST text id CDATA #REQUIRED>
	<!ELEMENT sentence (theme, rheme, semantic_roles)>
		<!ELEMENT theme (token*)>
		<!ELEMENT rheme (token*)>
		<!ELEMENT token (#PCDATA)>
		    <!ATTLIST token pos CDATA #REQUIRED>
		<!ELEMENT semantic_roles (frame*)>
		<!ELEMENT frame (argument*)>
            <!ATTLIST frame type CDATA #REQUIRED>
            <!ATTLIST frame head CDATA #REQUIRED>
		<!ELEMENT argument EMPTY>
            <!ATTLIST argument type CDATA #REQUIRED>
            <!ATTLIST argument dependent CDATA #REQUIRED>
]>


<text id="t6-5_ssd_annotated_recursive">


	<sentence>
		<theme>
			<token pos="di0fs0">una</token><token pos="aq0cs0">grácil</token><token pos="ncfs000">patinadora</token><token pos="aq0fs0">rubia</token>
		</theme>
		<rheme>
			<token pos="vmii3s0">anunciaba</token><token pos="di0fs0">una</token><token pos="ncfs000">marca</token><token pos="sps00">de</token><token pos="ncmp000">chocolates</token><token pos="sps00">de</token><token pos="np0000l">Valladolid</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="dp3cp0">sus</token><token pos="ncmp000">ojos</token>
		</theme>
		<rheme>
			<token pos="vmis3p0">distinguieron</token><token pos="di0fs0">una</token><token pos="ncfs000">mancha</token><token pos="aq0fs0">clara</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="da0ms0">El</token><token pos="ncms000">huerto</token>
		</theme>
		<rheme>
			<token pos="vmii3s0">estaba</token><token pos="fc">,</token><token pos="aq0cs0">arrogante</token><token pos="cc">e</token><token pos="aq0cs0">imposible</token><token pos="sps00">como</token><token pos="rg">siempre</token><token pos="fc">,</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			
		</theme>
		<rheme>
			
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


	<sentence>
		<theme>
			<token pos="pr000000">cuando</token><token pos="da0fs0">la</token><token pos="ncfs000">amargura</token><token pos="sps00">de</token><token pos="dd0ms0">aquel</token><token pos="ncms000">descubrimiento</token>
		</theme>
		<rheme>
			<token pos="p0300000">se</token><token pos="vaii3s0">había</token><token pos="vmp00sm">diluido</token><token pos="rg">poco</token><token pos="sps00">a</token><token pos="pi0cs000">poco</token><token pos="sps00">en</token><token pos="da0ms0">el</token><token pos="ncms000">transcurso</token><token pos="spcms">del</token><token pos="ncms000">tiempo</token><token pos="fc">,</token><token pos="rg">casi</token><token pos="dn0cp0">tres</token><token pos="ncmp000">años</token><token pos="sps00">de</token><token pos="ncfs000">vida</token><token pos="aq0cs0">igual</token><token pos="fc">,</token>
		</rheme>
		<semantic_roles>
		</semantic_roles>
	</sentence>


</text>